export const motivationQuotes = [
  { text: "L'excellence n'est jamais un accident. C'est toujours le résultat d'une intention élevée, d'un effort sincère et d'une exécution intelligente.", author: "Aristote" },
  { text: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill" },
  { text: "La seule façon de faire du bon travail est d'aimer ce que vous faites.", author: "Steve Jobs" },
  { text: "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.", author: "Eleanor Roosevelt" },

  // --- ↓ Ajout jusqu'à 100 pensées ↓ ---

  { text: "Votre vie s'améliore uniquement lorsque vous vous améliorez.", author: "Brian Tracy" },
  { text: "N'attendez pas. Le moment parfait n’arrivera jamais.", author: "Napoleon Hill" },
  { text: "Croyez en vous et tout deviendra possible.", author: "Audrey Hepburn" },
  { text: "Chaque progrès commence par la décision d'essayer.", author: "John F. Kennedy" },
  { text: "N'abandonnez jamais. Parfois la dernière clé du trousseau est celle qui ouvre la porte.", author: "Inconnu" },
  { text: "Vous êtes plus fort que vous ne le pensez.", author: "Inconnu" },
  { text: "Rêvez grand. Travaillez dur. Restez humble.", author: "Inconnu" },
  { text: "Le futur dépend de ce que vous faites aujourd'hui.", author: "Mahatma Gandhi" },
  { text: "Ne limite pas tes défis. Défi tes limites.", author: "Inconnu" },
  { text: "Le succès, c'est se relever une fois de plus que les autres.", author: "Oliver Goldsmith" },
  { text: "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.", author: "Nelson Mandela" },
  { text: "Fais de ta vie un rêve, et d'un rêve une réalité.", author: "Antoine de Saint-Exupéry" },
  { text: "Ce que tu obtiens en atteignant tes objectifs n’est pas aussi important que ce que tu deviens.", author: "Zig Ziglar" },
  { text: "La discipline est le pont entre les objectifs et les accomplissements.", author: "Jim Rohn" },
  { text: "Chaque jour est une nouvelle chance de changer votre vie.", author: "Inconnu" },
  { text: "Certaines personnes veulent que ça arrive, d'autres aimeraient que ça arrive, et d'autres font que ça arrive.", author: "Michael Jordan" },
  { text: "L'échec est le fondement de la réussite.", author: "Lao Tseu" },
  { text: "Le meilleur moment pour planter un arbre, c’était il y a 20 ans. Le deuxième meilleur moment, c’est maintenant.", author: "Proverbe chinois" },
  { text: "Travaille dur en silence, laisse ton succès faire le bruit.", author: "Inconnu" },
  { text: "Agissez comme s'il était impossible d'échouer.", author: "Dorothea Brande" },
  { text: "Ton seul limite, c’est toi.", author: "Inconnu" },
  { text: "Si vous voulez obtenir quelque chose que vous n'avez jamais eu, vous devez faire quelque chose que vous n'avez jamais fait.", author: "Thomas Jefferson" },
  { text: "Ne t’arrête pas lorsque tu es fatigué. Arrête-toi quand tu as terminé.", author: "Inconnu" },
  { text: "Ce n'est pas la force, mais la persévérance, qui fait les grandes œuvres.", author: "Samuel Johnson" },
  { text: "Votre seule limite est votre esprit.", author: "Inconnu" },
  { text: "Vous ne pouvez pas changer votre destination du jour au lendemain, mais vous pouvez changer votre direction immédiatement.", author: "Jim Rohn" },
  { text: "La motivation vous met en route, l'habitude vous fait continuer.", author: "Zig Ziglar" },
  { text: "N'abandonnez jamais un rêve à cause du temps que cela prendra pour le réaliser. Le temps passera de toute façon.", author: "Earl Nightingale" },
  { text: "Le succès n’est pas pour les plus talentueux, mais pour les plus déterminés.", author: "Inconnu" },
  { text: "Vos actions déterminent votre avenir.", author: "Inconnu" },
  { text: "Chaque accomplissement commence par la décision d’essayer.", author: "Gail Devers" },
  { text: "Le plus grand risque est de ne prendre aucun risque.", author: "Mark Zuckerberg" },
  { text: "Sans objectifs, tu ne peux les atteindre.", author: "Casey Neistat" },
  { text: "Peu importe la vitesse, avance.", author: "Inconnu" },
  { text: "Le plus grand plaisir dans la vie est d'accomplir ce que les autres vous pensent incapable de réaliser.", author: "Walter Bagehot" },
  { text: "La réussite appartient à tout le monde. C’est au travail d’équipe qu’en revient le mérite.", author: "Franck Piccard" },
  { text: "Chaque jour est une nouvelle opportunité de devenir meilleur.", author: "Inconnu" },
  { text: "Les gagnants trouvent des moyens, les perdants trouvent des excuses.", author: "Frank Sinatra" },
  { text: "La persévérance transforme le talent en succès.", author: "Inconnu" },
  { text: "L'échec n'est qu'une étape vers le succès.", author: "Inconnu" },
  { text: "Reste focus. Reste discipliné. Reste patient.", author: "Inconnu" },
  { text: "Un objectif sans plan est juste un souhait.", author: "Antoine de Saint-Exupéry" },
  { text: "Sois si bon qu'ils ne pourront pas t'ignorer.", author: "Steve Martin" },
  { text: "Ton futur commence maintenant.", author: "Inconnu" },
  { text: "Fais aujourd’hui ce que les autres ne veulent pas, pour vivre demain comme les autres ne peuvent pas.", author: "Inconnu" },
  { text: "La différence entre le possible et l’impossible se trouve dans la détermination.", author: "Tommy Lasorda" },
  { text: "La patience est amère, mais son fruit est doux.", author: "Aristote" },
  { text: "Celui qui déplace une montagne commence par déplacer de petites pierres.", author: "Confucius" },
  { text: "Rien n’est impossible à celui qui essaie.", author: "Alexandre le Grand" },
  { text: "Ce qui ne te tue pas te rend plus fort.", author: "Friedrich Nietzsche" },
  { text: "Votre futur se crée par ce que vous faites aujourd'hui.", author: "Inconnu" },
  { text: "Tout ce que l'esprit peut concevoir, il peut l'accomplir.", author: "Napoleon Hill" },
  { text: "Le succès est la somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
  { text: "Le progrès, pas la perfection.", author: "Inconnu" },
  { text: "L’échec est une redirection, pas une fin.", author: "Inconnu" },
  { text: "Tu deviens ce que tu crois.", author: "Oprah Winfrey" },
  { text: "Rêve sans peur, aime sans limite, avance sans doutes.", author: "Inconnu" },
  { text: "La constance bat le talent quand le talent n’est pas constant.", author: "Inconnu" },
  { text: "Ne regarde pas l’escalier en entier. Monte juste la première marche.", author: "Martin Luther King Jr." },
  { text: "Un voyage de mille kilomètres commence toujours par un pas.", author: "Lao Tseu" },
  { text: "Chaque jour est un second chance.", author: "Inconnu" },
  { text: "Si tu veux réussir, commence par croire que tu peux.", author: "Inconnu" },
  { text: "Tu n’es jamais trop vieux pour te fixer de nouveaux objectifs.", author: "C.S. Lewis" },
  { text: "Aucun vent n’est favorable à celui qui ne sait où il va.", author: "Sénèque" },
  { text: "Les petites actions répétées créent de grands résultats.", author: "Inconnu" },
  { text: "La magie opère quand tu n’abandonnes jamais.", author: "Inconnu" },
  { text: "La réussite commence par la volonté.", author: "Inconnu" },
  { text: "La confiance en soi est le premier secret du succès.", author: "Ralph Waldo Emerson" },
  { text: "Ne rêve pas ta vie, vis tes rêves.", author: "Inconnu" },
  { text: "La plus grande gloire n’est pas de ne jamais tomber, mais de se relever à chaque chute.", author: "Confucius" },
  { text: "L’effort d’aujourd’hui est la victoire de demain.", author: "Inconnu" },
  { text: "Tu es le seul responsable de ton succès.", author: "Inconnu" },
  { text: "Ce que tu fais chaque jour compte plus que ce que tu fais parfois.", author: "Inconnu" },
  { text: "La douleur est temporaire, la réussite est éternelle.", author: "Inconnu" },
  { text: "Garde ton esprit fort, ton cœur calme et ton chemin clair.", author: "Inconnu" },
  { text: "Chaque grande chose commence par une petite décision.", author: "Inconnu" },
  { text: "Le plus dur, c’est de commencer.", author: "Inconnu" },
  { text: "Si tu veux changer ta vie, change tes habitudes.", author: "Inconnu" },
  { text: "Vis chaque jour comme si c’était le premier et le dernier.", author: "Inconnu" },
  { text: "La clé du succès est la constance dans l’effort.", author: "Inconnu" },
  { text: "Tu n’as pas besoin d’être parfait pour avancer.", author: "Inconnu" },
  { text: "Ne laisse pas la peur décider de ton avenir.", author: "Inconnu" },
  { text: "Le travail bat le talent quand le talent ne travaille pas.", author: "Kevin Durant" }
];

// Fonction pour obtenir une citation aléatoire
export function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * motivationQuotes.length);
  return motivationQuotes[randomIndex];
}
